# Generated by Django 4.2.30 on 2026-04-08 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('substancja_aktywna', models.CharField(max_length=200)),
                ('instrukcja', models.TextField(help_text='Dawkowanie, pora dnia, z czym nie łączyć')),
                ('interakcje', models.ManyToManyField(blank=True, to='leki.lek', verbose_name='Interakcje z innymi lekami')),
            ],
            options={
                'verbose_name': 'Lek',
                'verbose_name_plural': 'Leki',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerty_interakcji', models.BooleanField(default=True)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil użytkownika',
            },
        ),
        migrations.CreateModel(
            name='PrzyjecieLeku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_godzina', models.DateTimeField()),
                ('status', models.CharField(choices=[('zazyte', 'Zażyte'), ('niezazyte', 'Niezażyte')], default='niezazyte', max_length=20)),
                ('notatka_samopoczucia', models.TextField(blank=True)),
                ('lek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przyjecia', to='leki.lek')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przyjecia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Przyjęcie leku',
                'verbose_name_plural': 'Przyjęcia leków',
                'ordering': ['-data_godzina'],
            },
        ),
    ]
