# Generated by Django 6.0.6 on 2026-06-12 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leki', '0002_lek_uzytkownik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lek',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena jednego opakowania w złotych', max_digits=8, null=True, verbose_name='Cena opakowania (zł)'),
        ),
        migrations.AddField(
            model_name='lek',
            name='ilosc_w_opakowaniu',
            field=models.PositiveIntegerField(blank=True, help_text='Np. 20 tabletek, 30 kapsułek', null=True, verbose_name='Liczba tabletek / dawek w opakowaniu'),
        ),
        migrations.AddField(
            model_name='lek',
            name='kod_kreskowy',
            field=models.CharField(blank=True, help_text='Wpisz lub zeskanuj kod z opakowania', max_length=30, verbose_name='Kod kreskowy (EAN)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_powiadomien',
            field=models.EmailField(blank=True, help_text='Zostaw puste, aby używać e-maila konta', max_length=254, verbose_name='E-mail do przypomnień'),
        ),
        migrations.CreateModel(
            name='HarmonogramPrzypomnienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godzina', models.TimeField(help_text='Format HH:MM, np. 08:00', verbose_name='Godzina przypomnienia')),
                ('aktywne', models.BooleanField(default=True)),
                ('lek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonogramy', to='leki.lek', verbose_name='Lek')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonogramy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Harmonogram przypomnienia',
                'verbose_name_plural': 'Harmonogramy przypomnień',
                'ordering': ['godzina'],
            },
        ),
    ]
